automated monthly extraction of ert flt and dly

diff --git a/data/set/ert_dly/extract_enroute_atfm_delay_fir_data b/data/set/ert_dly/extract_enroute_atfm_delay_fir_data
--- a/data/set/ert_dly/extract_enroute_atfm_delay_fir_data
+++ b/data/set/ert_dly/extract_enroute_atfm_delay_fir_data
@@ -7,9 +7,9 @@
 
 
 ##- Usage: extract_atfm_delay_fir_data [-f filename] WEF TIL
-##- Extract En-Route ATFM Delay (FIR based) data to csv file for the interval [WEF, TIL).
-##- WEF and TIL format is: YYYYMMDD, i.e. 20150301 (1st Mar 2015)
-##- Note: TIL is _not_ included.
+##- Extract En-Route ATFM Delay (FIR based) data to csv file, filename,
+##- for the interval [WEF, TIL). Note: TIL is _not_ included.
+##- WEF and TIL format is: YYYYMMDD, i.e. 20150301 (Mar 1, 2015)
 ##-
 ##- Assumptions:
 ##-   DBUSR                   environment variable for the relevant schema username.
@@ -18,27 +18,28 @@
 ##-
 ##-
 ##- Options:
-##-   -f, --file filename     The name of the file to save the output to (default 'ert_dly_<WEF YEAR><WEF MONTHNUM>.csv').
+##-   -f, --file filename     The name of the file to save the output to (default 'ert_dly_fir.csv').
 ##-   -h, --help              Print a usage message summarizing the command-line options, then exit.
 ##-   -V, --version           Output version information and exit.
 ##-
 ##- Examples:
-##- $ extract_enroute_atfm_delay_fir_data 20160101 20160201
+##- Extract data from Nov 11, 2015 to Dec 24, 2015
+##- $ extract_enroute_atfm_delay_fir_data 20151111 20151224
 ##-
 ##- Caveat: be sure to use gnu-getopt and not OSX builtin or Git Bash missing one ;-)
 
 
 SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
 SCRIPT=$(basename "${BASH_SOURCE[0]}")
-OUTPUT_FILENAME=''
+OUTPUT_FILENAME='ert_dly_fir.csv'
 
-help=$(grep "^##-" "${SCRIPT_DIR}/${SCRIPT}" | cut -c 4-)
-version=$(grep "^#--"  "${SCRIPT_DIR}/${SCRIPT}" | cut -c 4-)
 opt_h() {
+    help=$(grep "^##-" "${SCRIPT_DIR}/${SCRIPT}" | cut -c 4-)
     echo "$help"
 }
 
 opt_v() {
+    version=$(grep "^#--"  "${SCRIPT_DIR}/${SCRIPT}" | cut -c 4-)
     echo "$version"
 }
 
@@ -98,7 +99,7 @@ else
     if [[ ! ($1 =~ $WEFTIL_FORMAT) ]]
     then
         echo "Error: WEF is not a 8-digit number"
-        echo_h
+        opt_h
         exit 1
     fi
 
@@ -114,7 +115,7 @@ else
     if [[ ! ($2 =~ $WEFTIL_FORMAT) ]]
     then
         echo "Error: TIL is not a 8-digit number"
-        echo_h
+        opt_h
         exit 1
     fi
 
@@ -125,16 +126,15 @@ else
         opt_h
         exit 1
     fi
+
+    (( "$WEF" > "$TIL" )) && echo "Error: WEF > TIL" && exit 1
+
 fi
 
 
 
-WEF=$(date --date="$1" +"%d-%b-%Y" | tr '[:lower:]' '[:upper:]')
-YYYY=$(date --date="$1" +"%Y")
-MMMM=$(date --date="$1" +"%m")
-OUTPUT_FILENAME="ert_dly_fir_${YYYY}${MMMM}.csv"
-
-TIL=$(date --date="$2" +"%d-%b-%Y" | tr '[:lower:]' '[:upper:]')
+WEF=$(date --date="$WEF" +"%d-%b-%Y" | tr '[:lower:]' '[:upper:]')
+TIL=$(date --date="$TIL" +"%d-%b-%Y" | tr '[:lower:]' '[:upper:]')
 
 sql -S "$DBUSR"/"$DBPWD"@"$DBNAME" @En-Route_ATFM_Delay_FIR.sql "$OUTPUT_FILENAME" "'$WEF'" "'$TIL'"
 
diff --git a/data/set/ert_dly/extract_monthly_data b/data/set/ert_dly/extract_monthly_data
--- a/data/set/ert_dly/extract_monthly_data
+++ b/data/set/ert_dly/extract_monthly_data
@@ -120,14 +120,24 @@ else
         opt_h
         exit 1
     fi
+
+    (( "$WEF" > "$TIL" )) && echo "Error: WEF > TIL" && exit 1
 fi
 
-ts="$WEF"
-while [ "$ts" != "$TIL" ]; do
-    next=$(date -d "$ts +1 month" "+%Y%m%d")
+
+
+
+beg="$WEF"
+while (( "$beg" != "$TIL" )); do
+    next=$(date -d "$beg +1 month" "+%Y%m%d")
+
+    YYYY=$(date --date="$beg" +"%Y")
+    MMMM=$(date --date="$beg" +"%m")
+    OUTPUT_FILENAME="ert_dly_fir_${YYYY}${MMMM}.csv"
 
     "${SCRIPT_DIR}"/extract_enroute_atfm_delay_fir_data \
-                   "'$(date --date="$ts" +"%d-%b-%Y" | tr '[:lower:]' '[:upper:]')'" \
-                   "'$(date --date="$next" +"%d-%b-%Y" | tr '[:lower:]' '[:upper:]')'"
-    ts=$next
+                   -f "$OUTPUT_FILENAME" \
+                   "$beg" \
+                   "$next"
+    beg=$next
 done
diff --git a/data/set/ert_flt/extract_en-route_traffic_data b/data/set/ert_flt/extract_en-route_traffic_data
--- a/data/set/ert_flt/extract_en-route_traffic_data
+++ b/data/set/ert_flt/extract_en-route_traffic_data
@@ -6,11 +6,10 @@
 #-- Copyright (C) 2015 Eurocontrol/PRU
 
 
-##- Usage: extract_en-route_traffic_data <TIL>
-##- Extract Rn-route Traffic data to csv file, 'En-Route_Traffic.csv'
-##- from the period [WEF, TIL).
-##- WEF/TIL format: <YYYY><MM><DD>, i.e. 20160311 for Mar 11, 2016
-##- NOTE: <TIL> is not included
+##- Usage: extract_en-route_traffic_data [-f filename] WEF TIL
+##- Extract Rn-route Traffic data to csv file, filename,
+##- for the interval [WEF, TIL). Note: TIL is _not_ included.
+##- WEF/TIL format: <YYYY><MM><DD>, i.e. 20160311 ()Mar 11, 2016)
 ##-
 ##- Assumptions:
 ##-   DBUSR                   environment variable for the relevant schema username.
@@ -18,18 +17,19 @@
 ##-   DBNAME                  environment variable for the relevant schema name.
 ##-
 ##- Options:
+##-   -f, --file filename     The name of the file to save the output to (default 'ert_flt.csv').
 ##-   -h, --help              Print a usage message summarizing the command-line options, then exit.
 ##-   -V, --version           Output version information and exit.
 ##-
 ##- Examples:
 ##- Extract data from March 1, 2016 till Nov 11, 2016
-##- $ extract_en-route_traffic_data '20160301' '20161111'
+##- $ extract_en-route_traffic_data 20160301 20161111
 ##-
 ##- Caveat: be sure to use gnu-getopt and not OSX builtin or Git Bash missing one ;-)
 
 SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
 SCRIPT=$(basename "${BASH_SOURCE[0]}")
-OUTPUT_FILENAME='En-Route_Traffic.csv'
+OUTPUT_FILENAME='ert_flt.csv'
 
 opt_h() {
     help=$(grep "^##-" "${SCRIPT_DIR}/${SCRIPT}" | cut -c 4-)
@@ -57,6 +57,9 @@ unset TEMP
 
 while true; do
     case "$1" in
+        -f|--file)
+            OUTPUT_FILENAME="$2"; shift 2
+            ;;
         -h|--help)
             opt_h
             exit
@@ -93,7 +96,7 @@ else
     if [[ ! ($1 =~ $WEFTIL_FORMAT) ]]
     then
         echo "Error: WEF is not a 8-digit number"
-        echo_h
+        opt_h
         exit 1
     fi
 
@@ -109,7 +112,7 @@ else
     if [[ ! ($2 =~ $WEFTIL_FORMAT) ]]
     then
         echo "Error: TIL is not a 8-digit number"
-        echo_h
+        opt_h
         exit 1
     fi
 
@@ -120,12 +123,15 @@ else
         opt_h
         exit 1
     fi
+
+    (( "$WEF" > "$TIL" )) && echo "Error: WEF > TIL" && exit 1
+
 fi
 
 WEF=$(date --date="$WEF" +"%d-%b-%Y" | tr '[:lower:]' '[:upper:]')
 TIL=$(date --date="$TIL" +"%d-%b-%Y" | tr '[:lower:]' '[:upper:]')
 
-sql -S "$DBUSR"/"$DBPWD"@"$DBNAME" @en-route_traffic_csv.sql $OUTPUT_FILENAME "'$WEF'" "'$TIL'"
+sql -S "$DBUSR"/"$DBPWD"@"$DBNAME" @en-route_traffic_csv.sql "$OUTPUT_FILENAME" "'$WEF'" "'$TIL'"
 
 # remove blank lines in place
 sed -i -E 's/^ +//; s/ +$//; /^$/d' "$OUTPUT_FILENAME"
diff --git a/data/set/ert_flt/extract_en-route_traffic_fab_fir_data b/data/set/ert_flt/extract_en-route_traffic_fab_fir_data
--- a/data/set/ert_flt/extract_en-route_traffic_fab_fir_data
+++ b/data/set/ert_flt/extract_en-route_traffic_fab_fir_data
@@ -6,31 +6,32 @@
 #-- Copyright (C) 2015 Eurocontrol/PRU
 
 
-##- Usage: extract_en-route_traffic_fab_fir_data <WEF> <TIL>
-##- Extract En-route Traffic FAB FIR data to csv file, 'En-Route_Traffic_FAB_FIR.csv'
-##- from the period [WEF, TIL).
+##- Usage: extract_en-route_traffic_fab_fir_data [-f filename] <WEF> <TIL>
+##- Extract En-route Traffic at FAB FIR level to csv file, filename,
+##- for the interval [WEF, TIL). Note: TIL is _not_ included.
+##- WEF and TIL format is: YYYYMMDD, i.e. 20150301 (Mar 1, 2015)
 ##-
 ##- Assumptions:
 ##-   DBUSR                   environment variable for the relevant schema username.
 ##-   DBPWD                   environment variable for the relevant schema password.
 ##-   DBNAME                  environment variable for the relevant schema name.
 ##-
-##- ToDo:
-##-  * allow for an optional argument for the name of the file where to save to.
 ##-
 ##- Options:
+##-   -f, --file filename     The name of the file to save the output to (default 'ert_flt_fab_fir.csv').
 ##-   -h, --help              Print a usage message summarizing the command-line options, then exit.
 ##-   -V, --version           Output version information and exit.
 ##-
 ##- Examples:
-##- $ extract_en-route_traffic_fab_fir_data '20150101' '20160301'
+##- Extract data from Nov 11, 2015 to Dec 24, 2015
+##- $ extract_en-route_traffic_fab_fir_data 20151111 20151224
 ##-
 ##- Caveat: be sure to use gnu-getopt and not OSX builtin or Git Bash missing one ;-)
 
 SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
 SCRIPT=$(basename "${BASH_SOURCE[0]}")
 
-OUTPUT_FILENAME='En-Route_Traffic_FAB_FIR.csv'
+OUTPUT_FILENAME='ert_flt_fab_fir.csv'
 
 opt_h() {
     help=$(grep "^##-" "${SCRIPT_DIR}/${SCRIPT}" | cut -c 4-)
@@ -43,9 +44,8 @@ opt_v() {
 }
 
 
-
 # Execute getopt
-TEMP=$(getopt -o :hV --long ",help,version" -n "$SCRIPT" -- "$@");
+TEMP=$(getopt -o f:hV --long "file:help,version" -n "$SCRIPT" -- "$@");
 
 if [ $? != 0 ]
 then
@@ -58,6 +58,9 @@ unset TEMP
 
 while true; do
     case $1 in
+        -f|--file)
+            OUTPUT_FILENAME="$2"; shift 2
+            ;;
         -h|--help)
             opt_h
             exit 2
@@ -95,7 +98,7 @@ else
     if [[ ! ($1 =~ $WEFTIL_FORMAT) ]]
     then
         echo "Error: WEF is not a 8-digit number"
-        echo_h
+        opt_h
         exit 1
     fi
 
@@ -111,7 +114,7 @@ else
     if [[ ! ($2 =~ $WEFTIL_FORMAT) ]]
     then
         echo "Error: TIL is not a 8-digit number"
-        echo_h
+        opt_h
         exit 1
     fi
 
@@ -122,6 +125,9 @@ else
         opt_h
         exit 1
     fi
+
+    (( "$WEF" > "$TIL" )) && echo "Error: WEF > TIL" && exit 1
+
 fi
 
 WEF=$(date --date="$WEF" +"%d-%b-%Y" | tr '[:lower:]' '[:upper:]')
diff --git a/data/set/ert_flt/extract_monthly_data b/data/set/ert_flt/extract_monthly_data
--- a/data/set/ert_flt/extract_monthly_data
+++ b/data/set/ert_flt/extract_monthly_data
@@ -120,13 +120,22 @@ else
         opt_h
         exit 1
     fi
+
+    (( "$WEF" > "$TIL" )) && echo "Error: WEF > TIL" && exit 1
+
 fi
 
-ts="$WEF"
-while [ "$ts" != "$TIL" ]; do
-    next=$(date -d "$ts +1 month" "+%Y%m%d")
+beg="$WEF"
+while (( "$beg" < "$TIL" )); do
+    next=$(date -d "$beg +1 month" "+%Y%m%d")
 
-    extract_en-route_traffic_data "$ts" "$next"
-    extract_en-route_traffic_fab_fir_data "$ts" "$next"
-    ts=$next
+    YYYY=$(date --date="$beg" +"%Y")
+    MMMM=$(date --date="$beg" +"%m")
+
+    OUTPUT_FILENAME="ert_flt_${YYYY}${MMMM}.csv"
+    extract_en-route_traffic_data -f "$OUTPUT_FILENAME" "$beg" "$next"
+
+    OUTPUT_FILENAME="ert_flt_fab_fir_${YYYY}${MMMM}.csv"
+    extract_en-route_traffic_fab_fir_data -f "$OUTPUT_FILENAME" "$beg" "$next"
+    beg=$next
 done
