updated query for ANSP composition

diff --git a/data/set/ert_dly/extract_ansp_composition_data b/data/set/ert_dly/extract_ansp_composition_data
--- a/data/set/ert_dly/extract_ansp_composition_data
+++ b/data/set/ert_dly/extract_ansp_composition_data
@@ -6,8 +6,8 @@
 #-- Copyright (C) 2015 Eurocontrol/PRU
 
 
-##- Usage: extract_airport_atfm_delay_data
-##- Extract Airport Arrival ATFM Delay data to csv file, 'apt_dly.json' (this extension is a hack).
+##- Usage: extract_airport_atfm_delay_data DATE
+##- Extract ANSP composition data as of DATE to csv file, 'ansp_composition.csv'.
 ##-
 ##- Assumptions:
 ##-   DBUSR                   environment variable for the relevant schema username.
@@ -16,20 +16,21 @@
 ##-
 ##- ToDo:
 ##-  * allow for an optional argument for the name of the file where to save to.
-##-  * pass FROM and TO for the dates range of the data to be extracted.
 ##-
 ##- Options:
 ##-   -h, --help              Print a usage message summarizing the command-line options, then exit.
 ##-   -V, --version           Output version information and exit.
 ##-
 ##- Examples:
-##- $ extract_airport_atfm_delay_data
+##- Extract ANSP composition as of May 01, 2017
+##- $ extract_ansp_composition_data 20170501
 ##-
 ##- Caveat: be sure to use gnu-getopt and not OSX builtin or Git Bash missing one ;-)
 
 SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
 SCRIPT=$(basename "${BASH_SOURCE[0]}")
-OUTPUT_FILENAME=ansp_composition.csv
+OUTPUT_FILENAME="ansp_composition.csv"
+DATE_FILENAME="date_${OUTPUT_FILENAME%.*}.yml"
 
 
 # this is _the_ trick
@@ -84,14 +85,37 @@ while true; do
 done
 
 # there are NO mandatory arguments
-if (( $# != 0 )); then
+if (( $# != 1 )); then
     echo "Error: illegal number of parameters"
     opt_h
     exit 1
+else
+    DATE_FORMAT="^[0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9]$"
+
+    # test WEF is of correct format
+    if [[ ! ($1 =~ $DATE_FORMAT) ]]
+    then
+        echo "Error: DATE is not a 8-digit number"
+        opt_h
+        exit 1
+    fi
+
+    INSTANT=$(date --date="${1}" +"%Y%m%d" 2>/dev/null)
+    if [ -z "$INSTANT" ]
+    then
+        echo "Error: invalid DATE = $INSTANT"
+        opt_h
+        exit 1
+    fi
 fi
 
+INSTANT=$(date --date="$INSTANT" +"%d-%b-%Y" | tr '[:lower:]' '[:upper:]')
 
-sql -S "$DBUSR"/"$DBPWD"@"$DBNAME" @ansp_composition_csv.sql $OUTPUT_FILENAME
+sql -S "$DBUSR"/"$DBPWD"@"$DBNAME" @ansp_composition_csv.sql "$OUTPUT_FILENAME" "'$INSTANT'"
+
+# timestamp the date of the query
+echo "date: ${INSTANT}" > "$DATE_FILENAME"
 
 # remove blank lines in place
-sed -i -E 's/^ +//; s/ +$//; /^$/d' $OUTPUT_FILENAME
+sed -i -E 's/^ +//; s/ +$//; /^$/d' "$OUTPUT_FILENAME"
+sed -i -E 's/^ +//; s/ +$//; /^$/d' "$DATE_FILENAME"
