rationalized scripts and better input checks

diff --git a/data/set/apt_dly/extract_airport_atfm_delay_data b/data/set/apt_dly/extract_airport_atfm_delay_data
--- a/data/set/apt_dly/extract_airport_atfm_delay_data
+++ b/data/set/apt_dly/extract_airport_atfm_delay_data
@@ -23,67 +23,111 @@
 ##-   -V, --version           Output version information and exit.
 ##-
 ##- Examples:
-##- $ extract_airport_atfm_delay_data '01-JAN-2014' '01-JUN-2016'
+##- Extract data from Jan 1, 2014 to Jun 1, 2016 (excluded):
+##- $ extract_airport_atfm_delay_data 20140101 20160601
 ##-
 ##- Caveat: be sure to use gnu-getopt and not OSX builtin or Git Bash missing one ;-)
 
-SCRIPT=$(basename ${BASH_SOURCE[0]})
+SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
+SCRIPT=$(basename "${BASH_SOURCE[0]}")
 OUTPUT_FILENAME='apt_dly.json'  # this is a trick
 
-help=$(grep "^##-" "${SCRIPT}" | cut -c 4-)
-version=$(grep "^#--"  "${SCRIPT}" | cut -c 4-)
 opt_h() {
-  echo "$help"
+    help=$(grep "^##-" "${SCRIPT_DIR}/${SCRIPT}" | cut -c 4-)
+    echo "$help"
 }
 
 opt_v() {
-  echo "$version"
+    version=$(grep "^#--"  "${SCRIPT_DIR}/${SCRIPT}" | cut -c 4-)
+    echo "$version"
 }
 
 
 
 # Execute getopt
 TEMP=$(getopt -o :hV --long "help,version" -n "$SCRIPT" -- "$@");
+
+if [ $? != 0 ]
+then
+    echo "Invalid option(s): $*" >&2
+    exit 1
+fi
+
 eval set -- "$TEMP"
+unset TEMP
 
 while true; do
-   case $1 in
-   -h|--help)
-      opt_h
-      exit
-      ;;
-   -V|--version)
-      opt_v
-      exit
-      ;;
-   --)
-      shift
-      break
-      ;;
-   \?)
-      echo "Invalid option: -$OPTARG" >&2
-      opt_h
-      exit 1
-      ;;
-   *)
-      echo "Internal error!"
-      exit 1
-      ;;
-   esac
+    case $1 in
+        -h|--help)
+            opt_h
+            exit
+            ;;
+        -V|--version)
+            opt_v
+            exit
+            ;;
+        --)
+            shift
+            break
+            ;;
+        \?)
+            echo "Invalid option: -$OPTARG" >&2
+            opt_h
+            exit 1
+            ;;
+        *)
+            echo "Internal error!"
+            exit 1
+            ;;
+    esac
 done
+
 
 # there are two mandatory arguments
 if (( $# != 2 )); then
-   echo "Error: illegal number of parameters"
-   opt_h
-   exit 1
+    echo "Error: illegal number of parameters"
+    opt_h
+    exit 1
 else
-    WEF=$1
-    TIL=$2
+    WEFTIL_FORMAT="^[0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9]$"
+
+    # test WEF is of correct format
+    if [[ ! ($1 =~ $WEFTIL_FORMAT) ]]
+    then
+        echo "Error: WEF is not a 8-digit number"
+        echo_h
+        exit 1
+    fi
+
+    WEF=$(date --date="${1}" +"%Y%m%d" 2>/dev/null)
+    if [ -z "$WEF" ]
+    then
+        echo "Error: invalid WEF = $WEF"
+        opt_h
+        exit 1
+    fi
+
+    # test TIL is of correct format
+    if [[ ! ($2 =~ $WEFTIL_FORMAT) ]]
+    then
+        echo "Error: TIL is not a 8-digit number"
+        echo_h
+        exit 1
+    fi
+
+    TIL=$(date --date="${2}" +"%Y%m%d" 2>/dev/null)
+    if [ -z "$TIL" ]
+    then
+        echo "Error: invalid TIL = $TIL"
+        opt_h
+        exit 1
+    fi
 fi
 
+WEF=$(date --date="$WEF" +"%d-%b-%Y" | tr '[:lower:]' '[:upper:]')
+TIL=$(date --date="$WEF" +"%d-%b-%Y" | tr '[:lower:]' '[:upper:]')
 
-sql -S $DBUSR/$DBPWD@$DBNAME @airport_arrival_atfm_delay_csv.sql $OUTPUT_FILENAME $WEF $TIL
+sql -S "$DBUSR"/"$DBPWD"@"$DBNAME" @airport_arrival_atfm_delay_csv.sql $OUTPUT_FILENAME "'$WEF'" "'$TIL'"
 
 # remove blank lines in place
 sed -i -E 's/^ +//; s/ +$//; /^$/d' $OUTPUT_FILENAME
diff --git a/data/set/ert_dly/extract_enroute_atfm_delay_fir_data b/data/set/ert_dly/extract_enroute_atfm_delay_fir_data
--- a/data/set/ert_dly/extract_enroute_atfm_delay_fir_data
+++ b/data/set/ert_dly/extract_enroute_atfm_delay_fir_data
@@ -28,11 +28,12 @@
 ##- Caveat: be sure to use gnu-getopt and not OSX builtin or Git Bash missing one ;-)
 
 
-SCRIPT=$(basename ${BASH_SOURCE[0]})
+SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
+SCRIPT=$(basename "${BASH_SOURCE[0]}")
 OUTPUT_FILENAME=''
 
-help=$(grep "^##-" ${BASH_SOURCE} | cut -c 4-)
-version=$(grep "^#--"  "${BASH_SOURCE}" | cut -c 4-)
+help=$(grep "^##-" "${SCRIPT_DIR}/${SCRIPT}" | cut -c 4-)
+version=$(grep "^#--"  "${SCRIPT_DIR}/${SCRIPT}" | cut -c 4-)
 opt_h() {
     echo "$help"
 }
@@ -44,20 +45,28 @@ opt_v() {
 
 # Execute getopt
 TEMP=$(getopt -o f:hV --long "file:help,version" -n "$SCRIPT" -- "$@");
+
+if [ $? != 0 ]
+then
+    echo "Invalid option(s): $*" >&2
+    exit 1
+fi
+
 eval set -- "$TEMP"
+unset TEMP
 
 while true; do
-    case "$1" in
+    case $1 in
         -f|--file)
             OUTPUT_FILENAME="$2"; shift 2
             ;;
         -h|--help)
             opt_h
-            exit 2
+            exit
             ;;
         -V|--version)
             opt_v
-            exit 2
+            exit
             ;;
         --)
             shift
@@ -75,37 +84,59 @@ while true; do
     esac
 done
 
+
+
 # there are two mandatory arguments
 if (( $# != 2 )); then
     echo "Error: illegal number of parameters"
     opt_h
     exit 1
 else
-    WEF=$(date --date=$1 +"%d-%b-%Y")
-    if [ -z $WEF ]
+    WEFTIL_FORMAT="^[0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9]$"
+
+    # test WEF is of correct format
+    if [[ ! ($1 =~ $WEFTIL_FORMAT) ]]
     then
-        echo "Error: invalid WEF"
-        opt_h
+        echo "Error: WEF is not a 8-digit number"
+        echo_h
         exit 1
-    else
-        WEF=$(echo $WEF | tr '[:lower:]' '[:upper:]')
-        YYYY=$(date --date=$1 +"%Y")
-        MMMM=$(date --date=$1 +"%m")
-        OUTPUT_FILENAME="ert_dly_fir_${YYYY}${MMMM}.csv"
     fi
 
-    TIL=$(date --date=$2 +"%d-%b-%Y")
-    if [ -z $TIL ]
+    WEF=$(date --date="${1}" +"%Y%m%d" 2>/dev/null)
+    if [ -z "$WEF" ]
     then
-        echo "Error: invalid TIL"
+        echo "Error: invalid WEF = $WEF"
         opt_h
         exit 1
-    else
-        TIL=$(echo $TIL | tr '[:lower:]' '[:upper:]')
+    fi
+
+    # test TIL is of correct format
+    if [[ ! ($2 =~ $WEFTIL_FORMAT) ]]
+    then
+        echo "Error: TIL is not a 8-digit number"
+        echo_h
+        exit 1
+    fi
+
+    TIL=$(date --date="${2}" +"%Y%m%d" 2>/dev/null)
+    if [ -z "$TIL" ]
+    then
+        echo "Error: invalid TIL = $TIL"
+        opt_h
+        exit 1
     fi
 fi
 
-sql -S $DBUSR/$DBPWD@$DBNAME @En-Route_ATFM_Delay_FIR.sql $OUTPUT_FILENAME "'$WEF'" "'$TIL'"
+
+
+WEF=$(date --date="$1" +"%d-%b-%Y" | tr '[:lower:]' '[:upper:]')
+YYYY=$(date --date="$1" +"%Y")
+MMMM=$(date --date="$1" +"%m")
+OUTPUT_FILENAME="ert_dly_fir_${YYYY}${MMMM}.csv"
+
+TIL=$(date --date="$2" +"%d-%b-%Y" | tr '[:lower:]' '[:upper:]')
+
+sql -S "$DBUSR"/"$DBPWD"@"$DBNAME" @En-Route_ATFM_Delay_FIR.sql "$OUTPUT_FILENAME" "'$WEF'" "'$TIL'"
 
 # remove blank lines in place
-sed -i -E 's/^ +//; s/ +$//; /^$/d' $OUTPUT_FILENAME
+sed -i -E 's/^ +//; s/ +$//; /^$/d' "$OUTPUT_FILENAME"
diff --git a/data/set/ert_dly/extract_monthly_data b/data/set/ert_dly/extract_monthly_data
--- a/data/set/ert_dly/extract_monthly_data
+++ b/data/set/ert_dly/extract_monthly_data
@@ -29,11 +29,11 @@
 ##- Caveat: be sure to use gnu-getopt and not OSX builtin or Git Bash missing one ;-)
 
 
-SCRIPT=$(basename ${BASH_SOURCE[0]})
-OUTPUT_FILENAME=''
+SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
+SCRIPT=$(basename "${BASH_SOURCE[0]}")
 
-help=$(grep "^##-" ${BASH_SOURCE} | cut -c 4-)
-version=$(grep "^#--"  "${BASH_SOURCE}" | cut -c 4-)
+help=$(grep "^##-" "${SCRIPT_DIR}/${SCRIPT}" | cut -c 4-)
+version=$(grep "^#--"  "${SCRIPT_DIR}/${SCRIPT}" | cut -c 4-)
 opt_h() {
     echo "$help"
 }
@@ -45,7 +45,15 @@ opt_v() {
 
 # Execute getopt
 TEMP=$(getopt -o :hV --long ":help,version" -n "$SCRIPT" -- "$@");
+
+if [ $? != 0 ]
+then
+    echo "Invalid option(s): $*" >&2
+    exit 1
+fi
+
 eval set -- "$TEMP"
+unset TEMP
 
 while true; do
     case "$1" in
@@ -79,33 +87,47 @@ if (( $# != 2 )); then
     opt_h
     exit 1
 else
-    WEF=$(date --date="${1}01" +"%Y%m%d")
-    if [ -z $WEF ]
+    WEFTIL_FORMAT="^[0-9][0-9][0-9][0-9][0-9][0-9]$"
+
+    # test WEF is of correct format
+    if [[ ! ($1 =~ $WEFTIL_FORMAT) ]]
     then
-        echo "Error: invalid WEF"
-        opt_h
+        echo "Error: WEF is not a 6-digit number"
+        echo_h
         exit 1
-    else
-        declare -ri WEF_YYYY=$(( $(date --date=$WEF +"%Y") ))
-        declare -ri WEF_MMMM=$(( $(date --date=$WEF +"%m") ))
     fi
 
-    TIL=$(date --date="${2}01" +"%Y%m%d")
-    if [ -z $TIL ]
+    WEF=$(date --date="${1}01" +"%Y%m%d" 2>/dev/null)
+    if [ -z "$WEF" ]
     then
-        echo "Error: invalid TIL"
+        echo "Error: invalid WEF = $WEF"
         opt_h
         exit 1
-    else
-        declare -ri TIL_YYYY=$(( $(date --date=$TIL +"%Y") ))
-        declare -ri TIL_MMMM=$(( $(date --date=$TIL +"%m") ))
+    fi
+
+    # test TIL is of correct format
+    if [[ ! ($2 =~ $WEFTIL_FORMAT) ]]
+    then
+        echo "Error: TIL is not a 6-digit number"
+        echo_h
+        exit 1
+    fi
+
+    TIL=$(date --date="${2}01" +"%Y%m%d" 2>/dev/null)
+    if [ -z "$TIL" ]
+    then
+        echo "Error: invalid TIL = $TIL"
+        opt_h
+        exit 1
     fi
 fi
 
 ts="$WEF"
 while [ "$ts" != "$TIL" ]; do
     next=$(date -d "$ts +1 month" "+%Y%m%d")
-    echo $ts $next
-    extract_enroute_atfm_delay_fir_data $ts $next
+
+    "${SCRIPT_DIR}"/extract_enroute_atfm_delay_fir_data \
+                   "'$(date --date="$ts" +"%d-%b-%Y" | tr '[:lower:]' '[:upper:]')'" \
+                   "'$(date --date="$next" +"%d-%b-%Y" | tr '[:lower:]' '[:upper:]')'"
     ts=$next
 done
diff --git a/scripts/updateCSV b/scripts/updateCSV
--- a/scripts/updateCSV
+++ b/scripts/updateCSV
@@ -29,85 +29,92 @@
 SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
 SCRIPT="$(basename "${BASH_SOURCE[0]}")"
 
-help=$(grep "^##-" "${SCRIPT}" | cut -c 4-)
-version=$(grep "^#--"  "${SCRIPT}" | cut -c 4-)
+help=$(grep "^##-" "${SCRIPT_DIR}/${SCRIPT}" | cut -c 4-)
+version=$(grep "^#--"  "${SCRIPT_DIR}/${SCRIPT}" | cut -c 4-)
 
 opt_h() {
-  echo "$help"
+    echo "$help"
 }
 
 opt_v() {
-  echo "$version"
+    echo "$version"
 }
 
 
 # Execute getopt
 TEMP=$(getopt -o :hV --long "help,version" -n "${SCRIPT}" -- "$@");
+
+if [ $? != 0 ]
+then
+    echo "Invalid option(s): $*" >&2
+    exit 1
+fi
+
 eval set -- "$TEMP"
 unset TEMP
 
 while true; do
-   case $1 in
-   -h|--help)
-      opt_h
-      exit
-      ;;
-   -V|--version)
-      opt_v
-      exit
-      ;;
-   --)
-      shift
-      break
-      ;;
-   \?)
-      echo "Invalid option: -$OPTARG" >&2
-      opt_h
-      exit 1
-      ;;
-   *)
-      echo "Internal error!"
-      exit 1
-      ;;
-   esac
+    case $1 in
+        -h|--help)
+            opt_h
+            exit
+            ;;
+        -V|--version)
+            opt_v
+            exit
+            ;;
+        --)
+            shift
+            break
+            ;;
+        \?)
+            echo "Invalid option: -$OPTARG" >&2
+            opt_h
+            exit 1
+            ;;
+        *)
+            echo "Internal error!"
+            exit 1
+            ;;
+    esac
 done
 
 # there are NO mandatory arguments
 if (( $# != 0 )); then
-   echo "Error: illegal number of parameters"
-   opt_h
-   exit 1
+    echo "Error: illegal number of parameters"
+    opt_h
+    exit 1
 fi
 
 
 (
-    cd ${SCRIPT_DIR}/../data/set/hfe;
+    cd "${SCRIPT_DIR}/../data/set/hfe" || exit;
     DBUSR=$HFEDBUSR DBPWD=$HFEDBPWD ./extract_horizontal_flight_efficiency_data;
 )
 
 (
-    cd ${SCRIPT_DIR}/../data/set/ert_flt;
+    cd "${SCRIPT_DIR}/../data/set/ert_flt" || exit;
     DBUSR=$YYYDBUSR DBPWD=$YYYDBPWD ./extract_en-route_traffic_fab_fir_data '01-JAN-2015' '01-SEP-2016';
-    cp -f En-Route_Traffic_FAB_FIR.csv ${SCRIPT_DIR}/../graphics/en-route_atfm_delay_fab/
+    cp -f En-Route_Traffic_FAB_FIR.csv "${SCRIPT_DIR}/../graphics/en-route_atfm_delay_fab/"
 )
 
 (
-    cd ${SCRIPT_DIR}/../data/set/ert_dly;
+    cd "${SCRIPT_DIR}/../data/set/ert_dly" || exit;
     DBUSR=$YYYDBUSR DBPWD=$YYYDBPWD ./extract_ansp_composition_data;
-    mv -f ansp_composition.csv ${SCRIPT_DIR}/../_data/.
+    mv -f ansp_composition.csv "${SCRIPT_DIR}/../_data/."
 )
 
 ######### extract monthly file for ert_dly ###########
 # limit to latest months not yet in data/csv directory
 (
-    cd ${SCRIPT_DIR}/../data/set/ert_dly;
+    cd "${SCRIPT_DIR}/../data/set/ert_dly" || exit;
     DBUSR=$YYYDBUSR DBPWD=$YYYDBPWD ./extract_monthly_data 201609 201610;
-    mv -f ert_dly_fir_*.csv ${SCRIPT_DIR}/../_data/csv/.
+    mv -f ert_dly_fir_*.csv "${SCRIPT_DIR}/../_data/csv/."
 )
 
 
 (
-    cd ${SCRIPT_DIR}/../data/set/apt_dly;
+    cd "${SCRIPT_DIR}/../data/set/apt_dly" || exit;
     DBUSR=$YYYDBUSR DBPWD=$YYYDBPWD ./extract_airport_atfm_delay_data '01-JAN-2014' '01-SEP-2016';
 )
 
